#!/bin/bash
# scripts/lib.sh — shared helpers for install / operate / cleanup.
# This file is sourced, not executed.

# --- argument parsing ---------------------------------------------------
# Usage: parse_args "$@"
# Sets globals: OPENRC, TAG, SSH_KEY (absolute paths)
parse_args() {
    if [ $# -ne 3 ]; then
        echo "Usage: $0 <openrc> <tag> <ssh_key>" >&2
        exit 1
    fi
    OPENRC=$(readlink -f "$1")
    TAG="$2"
    SSH_KEY=$(readlink -f "$3")

    [ -f "$OPENRC" ]      || { echo "openrc not found: $OPENRC" >&2; exit 1; }
    [ -f "$SSH_KEY" ]     || { echo "ssh private key not found: $SSH_KEY" >&2; exit 1; }
    [ -f "${SSH_KEY}.pub" ] || { echo "ssh public key not found: ${SSH_KEY}.pub" >&2; exit 1; }
}

# --- locate project root -----------------------------------------------
locate_project_root() {
    PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[1]}")" && pwd)"
    TF_DIR="$PROJECT_ROOT/terraform"
    ANSIBLE_DIR="$PROJECT_ROOT/ansible"
    SCRIPTS_DIR="$PROJECT_ROOT/scripts"
}

# --- timestamped logging -----------------------------------------------
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') $*"
}

# --- source openrc -----------------------------------------------------
# If OS_PASSWORD is already set in the environment (i.e. the user sourced
# the openrc in their shell already), reuse it. Otherwise source the file,
# which will prompt the user once.
source_openrc() {
    if [ -n "${OS_PASSWORD:-}" ] && [ -n "${OS_AUTH_URL:-}" ]; then
        log "OpenStack credentials already in environment — reusing them"
        return 0
    fi
    log "Sourcing openrc: $OPENRC"
    set +u
    # shellcheck disable=SC1090
    source "$OPENRC"
    set -u
    if [ -z "${OS_AUTH_URL:-}" ] || [ -z "${OS_USERNAME:-}" ]; then
        echo "openrc did not set OS_AUTH_URL / OS_USERNAME" >&2
        exit 1
    fi
    if [ -z "${OS_PASSWORD:-}" ]; then
        echo "OS_PASSWORD is empty after sourcing openrc — did you type it?" >&2
        exit 1
    fi
}

# --- ensure two floating IPs (reuse if possible) -----------------------
# Echoes 2 floating IP addresses on stdout (one per line).
# All other output goes to stderr.
# Newly-allocated FIPs are tagged with $TAG so cleanup can find them.
ensure_two_floating_ips() {
    local pool="${1:-External}"

    # List existing FIPs that are NOT associated with anything.
    # Output format from openstack: "<addr> None" if unassigned.
    local unused
    unused=$(openstack floating ip list -f value -c "Floating IP Address" -c "Port" \
             | awk '$2 == "None" {print $1}')

    local fips=()
    while IFS= read -r ip; do
        [ -n "$ip" ] && fips+=("$ip")
    done <<< "$unused"

    log "Found ${#fips[@]} unassigned floating IP(s) in project" >&2

    while [ ${#fips[@]} -lt 2 ]; do
        log "Allocating new floating IP from pool '$pool'" >&2
        local new
        new=$(openstack floating ip create "$pool" --tag "$TAG" \
              -f value -c floating_ip_address)
        fips+=("$new")
        log "Allocated $new (tagged $TAG)" >&2
    done

    printf '%s\n' "${fips[0]}" "${fips[1]}"
}

# --- read desired node count from servers.conf ------------------------
read_desired_count() {
    local conf="$PROJECT_ROOT/servers.conf"
    [ -f "$conf" ] || { echo "servers.conf not found at $conf" >&2; exit 1; }
    grep -v '^#' "$conf" | grep -v '^[[:space:]]*$' | head -n1 | awk '{print $1}'
}

# --- generate ansible/inventory.ini and SSH config from terraform output -
# Call after terraform apply has succeeded.
generate_inventory_and_sshconfig() {
    local proxy_pub="$1"
    local bastion_pub="$2"
    local proxy_priv="$3"
    local bastion_priv="$4"
    local node_priv_json="$5"
    local node_names_json="$6"

    local ssh_config="$PROJECT_ROOT/${TAG}_SSHconfig"
    local inventory="$ANSIBLE_DIR/inventory.ini"

    log "Writing SSH config to $ssh_config"
    {
        echo "# Generated by install — do not edit"
        echo
        echo "Host ${TAG}_bastion"
        echo "    HostName $bastion_pub"
        echo "    User ubuntu"
        echo "    IdentityFile $SSH_KEY"
        echo "    StrictHostKeyChecking no"
        echo "    UserKnownHostsFile /dev/null"
        echo "    LogLevel ERROR"
        echo
        echo "Host ${TAG}_proxy"
        echo "    HostName $proxy_priv"
        echo "    User ubuntu"
        echo "    IdentityFile $SSH_KEY"
        echo "    StrictHostKeyChecking no"
        echo "    UserKnownHostsFile /dev/null"
        echo "    LogLevel ERROR"
        echo "    ProxyJump ${TAG}_bastion"
        echo

        local privs names
        privs=$(echo "$node_priv_json" | python3 -c 'import json,sys;print("\n".join(json.load(sys.stdin)))')
        names=$(echo "$node_names_json" | python3 -c 'import json,sys;print("\n".join(json.load(sys.stdin)))')

        paste <(echo "$names") <(echo "$privs") | while IFS=$'\t' read -r name ip; do
            [ -z "$name" ] && continue
            echo "Host $name"
            echo "    HostName $ip"
            echo "    User ubuntu"
            echo "    IdentityFile $SSH_KEY"
            echo "    StrictHostKeyChecking no"
            echo "    UserKnownHostsFile /dev/null"
            echo "    LogLevel ERROR"
            echo "    ProxyJump ${TAG}_bastion"
            echo
        done
    } > "$ssh_config"

    log "Writing Ansible inventory to $inventory"
    {
        echo "[bastion]"
        echo "${TAG}_bastion ansible_host=$bastion_pub"
        echo
        echo "[proxy]"
        echo "${TAG}_proxy ansible_host=$proxy_priv"
        echo
        echo "[nodes]"
        local privs names
        privs=$(echo "$node_priv_json" | python3 -c 'import json,sys;print("\n".join(json.load(sys.stdin)))')
        names=$(echo "$node_names_json" | python3 -c 'import json,sys;print("\n".join(json.load(sys.stdin)))')
        paste <(echo "$names") <(echo "$privs") | while IFS=$'\t' read -r name ip; do
            [ -z "$name" ] && continue
            echo "$name ansible_host=$ip"
        done
        echo
        echo "[all:vars]"
        echo "ansible_user=ubuntu"
        echo "ansible_ssh_private_key_file=$SSH_KEY"
        echo "ansible_ssh_common_args='-F $ssh_config'"
    } > "$inventory"
}
