#!/bin/bash
# Shared helpers for install / operate / cleanup. Source this; do not execute.

parse_args() {
    if [ $# -ne 3 ]; then
        echo "Usage: $0 <openrc> <tag> <ssh_key>" >&2
        exit 1
    fi
    OPENRC=$(readlink -f "$1")
    TAG="$2"
    SSH_KEY=$(readlink -f "$3")

    [ -f "$OPENRC" ]        || { echo "openrc not found: $OPENRC" >&2; exit 1; }
    [ -f "$SSH_KEY" ]       || { echo "ssh private key not found: $SSH_KEY" >&2; exit 1; }
    [ -f "${SSH_KEY}.pub" ] || { echo "ssh public key not found: ${SSH_KEY}.pub" >&2; exit 1; }
}

locate_project_root() {
    PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[1]}")" && pwd)"
    TF_DIR="$PROJECT_ROOT/terraform"
    ANSIBLE_DIR="$PROJECT_ROOT/ansible"
    SCRIPTS_DIR="$PROJECT_ROOT/scripts"
}

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') $*"
}

# Reuse credentials from the shell if openrc was already sourced; otherwise
# source the file (which will prompt for the password).
source_openrc() {
    if [ -n "${OS_PASSWORD:-}" ] && [ -n "${OS_AUTH_URL:-}" ]; then
        log "OpenStack credentials already in environment"
        return 0
    fi
    log "Sourcing openrc: $OPENRC"
    set +u
    # shellcheck disable=SC1090
    source "$OPENRC"
    set -u
    if [ -z "${OS_AUTH_URL:-}" ] || [ -z "${OS_USERNAME:-}" ]; then
        echo "openrc did not set OS_AUTH_URL / OS_USERNAME" >&2
        exit 1
    fi
    if [ -z "${OS_PASSWORD:-}" ]; then
        echo "OS_PASSWORD is empty after sourcing openrc" >&2
        exit 1
    fi
}

# Reuse any unassigned floating IPs in the project before allocating new ones.
# Newly-allocated IPs get tagged with $TAG so cleanup can find them.
ensure_two_floating_ips() {
    local pool="${1:-External}"

    local unused
    unused=$(openstack floating ip list -f value -c "Floating IP Address" -c "Port" \
             | awk '$2 == "None" {print $1}')

    local fips=()
    while IFS= read -r ip; do
        [ -n "$ip" ] && fips+=("$ip")
    done <<< "$unused"

    log "Found ${#fips[@]} unassigned floating IP(s)" >&2

    while [ ${#fips[@]} -lt 2 ]; do
        local new
        new=$(openstack floating ip create "$pool" --tag "$TAG" \
              -f value -c floating_ip_address)
        fips+=("$new")
        log "Allocated $new" >&2
    done

    printf '%s\n' "${fips[0]}" "${fips[1]}"
}

read_desired_count() {
    local conf="$PROJECT_ROOT/servers.conf"
    [ -f "$conf" ] || { echo "servers.conf not found at $conf" >&2; exit 1; }
    grep -v '^#' "$conf" | grep -v '^[[:space:]]*$' | head -n1 | awk '{print $1}'
}

# Decode a JSON array of strings (from `terraform output -json`) into a
# newline-separated list of values.
_json_array_to_lines() {
    python3 -c 'import json,sys;print("\n".join(json.load(sys.stdin)))'
}

_emit_ssh_host() {
    local name="$1" host="$2" with_jump="$3"
    echo "Host $name"
    echo "    HostName $host"
    echo "    User ubuntu"
    echo "    IdentityFile $SSH_KEY"
    echo "    StrictHostKeyChecking no"
    echo "    UserKnownHostsFile /dev/null"
    echo "    LogLevel ERROR"
    [ "$with_jump" = "yes" ] && echo "    ProxyJump ${TAG}_bastion"
    echo
}

# Block until every Host entry in the SSH config accepts an SSH connection.
wait_for_ssh() {
    local ssh_config="$PROJECT_ROOT/${TAG}_SSHconfig"
    local timeout="${1:-480}"
    local deadline=$(( $(date +%s) + timeout ))

    local hosts
    hosts=$(awk '/^Host / && $2 != "*" {print $2}' "$ssh_config")

    for host in $hosts; do
        log "  Waiting for $host"
        while [ "$(date +%s)" -lt "$deadline" ]; do
            if ssh -F "$ssh_config" -o ConnectTimeout=5 -o BatchMode=yes \
                   "$host" 'echo ok' >/dev/null 2>&1; then
                log "    $host is reachable"
                break
            fi
            sleep 5
        done
    done
}

# Inline the ProxyCommand into the inventory so Ansible doesn't pick up
# unrelated entries from ~/.ssh/config (e.g. a previous course project).
generate_inventory_and_sshconfig() {
    local proxy_pub="$1" bastion_pub="$2"
    local proxy_priv="$3" bastion_priv="$4"
    local node_priv_json="$5" node_names_json="$6"

    local ssh_config="$PROJECT_ROOT/${TAG}_SSHconfig"
    local inventory="$ANSIBLE_DIR/inventory.ini"

    local common="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    local jump="-o ProxyCommand='ssh -F none ${common} -i ${SSH_KEY} -W %h:%p ubuntu@${bastion_pub}'"

    local privs names
    privs=$(echo "$node_priv_json"  | _json_array_to_lines)
    names=$(echo "$node_names_json" | _json_array_to_lines)

    log "Writing SSH config to $ssh_config"
    {
        echo "# Generated by install"
        echo
        _emit_ssh_host "${TAG}_bastion" "$bastion_pub" no
        _emit_ssh_host "${TAG}_proxy"   "$proxy_priv"  yes
        paste <(echo "$names") <(echo "$privs") | while IFS=$'\t' read -r name ip; do
            [ -z "$name" ] && continue
            _emit_ssh_host "$name" "$ip" yes
        done
    } > "$ssh_config"

    log "Writing Ansible inventory to $inventory"
    {
        echo "[bastion]"
        echo "${TAG}_bastion ansible_host=${bastion_pub} ansible_ssh_common_args=\"${common}\""
        echo
        echo "[proxy]"
        echo "${TAG}_proxy ansible_host=${proxy_priv} ansible_ssh_common_args=\"${common} ${jump}\""
        echo
        echo "[nodes]"
        paste <(echo "$names") <(echo "$privs") | while IFS=$'\t' read -r name ip; do
            [ -z "$name" ] && continue
            echo "${name} ansible_host=${ip} ansible_ssh_common_args=\"${common} ${jump}\""
        done
        echo
        echo "[all:vars]"
        echo "ansible_user=ubuntu"
        echo "ansible_ssh_private_key_file=$SSH_KEY"
    } > "$inventory"
}
